"""
Django settings for emailcelery project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qklf0p_i7+85cg*$f@e^5r_c_gis6ncws6cqh@8i$hb0qg#ya6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'send_mail_app',
    'django_celery_results',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'emailcelery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emailcelery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





#CELERY BEAT
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# SMTP Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER ='booklandz911@gmail.com'
EMAIL_HOST_PASSWORD = "zrrlxdirzbmdbloo"
DEFAULT_FROM_EMAIL = 'Celery <booklandz911@gmail.com>'

# CELERY SETTINGS

# CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Kolkata'
# CELERY_RESULT_BACKEND = 'django-db'

#
CELERY_BROKER_URL = "sqs://"
CELERY_TASK_DEFAULT_QUEUE = "CeleryBroker"
CELERY_TASK_CREATE_MISSING_QUEUES: bool = False
CELERY_WORKER_ENABLE_REMOTE_CONTROL: bool = False
CELERY_WORKER_SEND_TASK_EVENTS: bool = False
CELERY_BROKER_USER = 'AKIA2XJHCOCGWYCCYP6K'
CELERY_BROKER_PASSWORD = 'lEWgwD3W4dbpbdO1jgBCiwFk280EFpoivdTulFZG'
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "predefined_queues": {
        "CeleryBroker": {
            "url": "https://sqs.us-east-1.amazonaws.com/737205710989/CeleryBroker",
        },
    },
}


# CELERY_BROKER_TRANSPORT = 'sqs'
# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     'region': 'us-east-1',
# }
# CELERY_BROKER_USER = 'AKIA2XJHCOCGWYCCYP6K'
# CELERY_BROKER_PASSWORD = 'lEWgwD3W4dbpbdO1jgBCiwFk280EFpoivdTulFZG'
#
# CELERY_DEFAULT_QUEUE = 'CeleryBroker'
# CELERY_QUEUES = {
#     CELERY_DEFAULT_QUEUE: {
#         'exchange': CELERY_DEFAULT_QUEUE,
#         'binding_key': CELERY_DEFAULT_QUEUE,
#     }
# }